#spring.application.name=security

#this is the header so every thing after it will be from spring
spring:
#same as here
  datasource:
#    spring.datasource.url
    url: jdbc:postgresql://localhost:5432/postgres
    #spring.datasource.username=postgres
    username: postgres
    #spring.datasource.password=postgres
    password: postgres
#    this the driver class
    driver-class: org.postgresql.Driver
  jpa:
    hibernate:
#      spring.jpa.hibernate.ddl-auto
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
#    this for  dialect that help hibernate to translate into understandable sql lang
    database-perform: org.hibernate.dialect.PostgreSQLDialect